#####################################################################################################################
#####################################################################################################################
FROM golang:alpine3.18 as builder
RUN apk --no-cache add ca-certificates

#SET WORKING DIRECTORY FOR PROJECT AND GOROOT
WORKDIR $GOPATH/cloudsync

#DOWNLOAD MODULES
COPY go.mod go.sum ./
RUN go mod download

# PREPARE SOURCES
COPY . .

# HANDLER BUILD ARGUMENTS
ARG COMMIT=1
ARG BUILD=1
ARG RELEASE_DATE='2023-01-01 12:00:00'
ARG VERSION=v0.0.0

ENV COMMIT=${COMMIT}
ENV BUILD=${BUILD}
ENV RELEASE_DATE=${RELEASE_DATE}
ENV VERSION=${VERSION}

#BUILD
RUN GOOS=linux GOARCH=amd64 go build -ldflags "-X 'cloudsync/cmd.version=$VERSION' -X 'cloudsync/cmd.commit=$COMMIT' -X 'cloudsync/cmd.build=$BUILD' -X 'cloudsync/cmd.releaseDate=$RELEASE_DATE' -s -w" -a -o /tmp/builder/cloudsync

#TEST COMMANDS
RUN /tmp/builder/cloudsync version

######################################################################################################################
######################################################################################################################
FROM scratch
WORKDIR /usr/local/bin

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /etc/passwd /etc/passwd

COPY --from=builder /tmp/builder/cloudsync .
ENTRYPOINT [ "cloudsync" ]